return {
  --   { "mcchrish/zenbones.nvim", dependencies = {
  --     "rktjmp/lush.nvim",
  --   } },
  --   {
  --     "folke/tokyonight.nvim",
  --     lazy = false,
  --     priority = 1000,
  --     opts = {},
  --   },
  --   { "fynnfluegge/monet.nvim" },
  --   { "Shatur/neovim-ayu" },
  --   { "ellisonleao/gruvbox.nvim" },
  --   { "catppuccin/nvim", name = "catppuccin" },
  --   {
  --     "LazyVim/LazyVim",
  --     opts = {
  --       colorscheme = "tokyobones",
  --     },
  --   },
}
